"""
Thin wrapper around the AI lead's LLM module (resume parsing + comparison explanation).

Replace the bodies of these functions with real calls into their module once it's ready, e.g.:
    from ai_module import llm_client as real_llm

Until then, each function returns reasonable mock output so the rest of the backend can be
built and tested independently.
"""

import uuid
from app.models import Candidate

# TODO: once AI lead's module is ready, import it here, e.g.:
# import resume_ai

USE_REAL_LLM = False  # flip to True once the AI lead's module is wired in


async def parse_resume(resume_text: str, candidate_id: str, source_filename: str = None) -> Candidate:
    """
    Takes raw resume text, returns a structured Candidate.
    candidate_id is generated by the backend (upload.py) and passed in so the ID stays
    consistent across candidate_store, Cognee, and the frontend.
    """
    # TODO: replace with real LLM module call from teammate
    # e.g. parsed = await resume_ai.parse_resume(resume_text)
    if USE_REAL_LLM:
        raise NotImplementedError("Wire in AI lead's real parse_resume() here")

    # Mock fallback: naive placeholder so /upload works end-to-end before real parsing exists
    return Candidate(
        id=candidate_id,
        name="Unknown Candidate (mock parse)",
        skills=[],
        experience_years=0.0,
        source_filename=source_filename,
    )


async def explain_comparison(candidate_a: Candidate, candidate_b: Candidate) -> str:
    # TODO: replace with real LLM module call from teammate
    # e.g. return await resume_ai.explain_comparison(candidate_a, candidate_b)
    if USE_REAL_LLM:
        raise NotImplementedError("Wire in AI lead's real explain_comparison() here")

    return (
        f"[mock explanation] {candidate_a.name} has {len(candidate_a.skills)} listed skills "
        f"and {candidate_a.experience_years} years experience, compared to {candidate_b.name} "
        f"with {len(candidate_b.skills)} skills and {candidate_b.experience_years} years."
    )
